/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 7.5 */
/* Tue May 26 10:36:14 2026 */

/* parameterized module instance */
RAM __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), .Data( ), 
    .Q( ));
