/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.4 */
/* Thu May 28 16:28:55 2026 */

/* parameterized module instance */
rom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
